### ISSUE TITLE
My suggestions

### ISSUE THREAD

**Issue by piano777wzy** [Alando1-doom/Toby-Accessibility-Mod-for-Doom#142]
Hello! I have used the latest source code of GitHub and downloaded and loaded it into the game.

I would like to put forward two suggestions.

1. For the area scanning system, that is, by pressing the letter "v", the output method of "Toby_NarrationOutputType=2" can be used. This is convenient for screen readers. I really don't like the default voice function in it because I completely don't understand what it is saying. If it can be output to the screen reader, I can translate it.
2. I don't know why after changing "Toby_NarrationOutputType" to 2, functions such as pressing the letter keys "f", "e", "r", "q", that is, the direction compass function, will be read out together by the built-in voice and the screen reader. I don't know why this is.

In addition, regarding the importance of the first content, it is very important to use "Toby_NarrationOutputType=2" for the area scanning system output. Many people around me say that this function is very important. Currently, only this content is missing for the screen reader.

Thanks again for your development.

**Comment by proydoha** [comment]
@piano777wzy Hello!

1. It is important, I agree. The reason why its not done yet is because it is kind of a mess of a feature and there are two approaches to update it: relatively quick and very dirty and a complete rewrite. Both are on on my mind, I just don't have time to work on it currently.
2. Compass is ACS, I haven't touched it for this reason. You actually shouldn't hear screen reader output because its not handled by the mod. Its probably gets picked up by the script that stormdragon2976 made. But if you do hear screen reader output then as a temporary solution you can disable narration by loading this mod at the end (unpack it, pk3 is inside, GitHub disallows me to upload .pk3 directly):
[Toby-Disable-Compass-Narration.zip](https://github.com/user-attachments/files/17534006/Toby-Disable-Compass-Narration.zip)
In any case, its on the list of improvement that we should do.

I'm going to close it as duplicate because we have this issue: #129
