### ISSUE TITLE
[Bug] Sound emitters for doors and switches are killed by "kill monsters" console command

### ISSUE THREAD

**Issue by proydoha** [Alando1-doom/Toby-Accessibility-Mod-for-Doom#161]
I think sounds for regular (not locked) doors and switches no longer work ( ? )

**Comment by proydoha** [comment]
After further investigation I've discovered that they are removed when "kill monsters" command is run

**Comment by Alando1-doom** [comment]
I was doing some research into alternative options and I did find something we could use. I noticed a flag on the ZDoom wiki called +NODAMAGE. This would make the "Monsters" invulnerable to the "Kill Monsters" console command. Perhaps we could combine our ideas. I like how you were able to clean up the scripts via inheritance and to simplify everything as a whole. We can still keep these door/switch beacons as "Monsters." I will apply +NODAMAGE to the Key Door Beacons as well since they, too, are "Monsters." What do you think of this idea?

**Comment by proydoha** [comment]
Fixed by #167
